apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
  namespace: default
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      # endpointAddress: "http://zipkin-srv:9411/api/v2/spans"
      endpointAddress: "http://jaeger-operator-srv:9411/api/v2/spans"
